djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from .views  import home_view

urlpatterns = [
   path('', home_view),
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('', views.question_list, name='question_list'),
]
urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),
]

chat/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')




class Answer(models.Model):
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Answer(models.Model):
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)

chat/views.py
from django.shortcuts import render

# Create your views here.

djangoProject1/views.py
from django.shortcuts import render

def home_view(request):
   print(request)
   print(request.user)


   return render(request, 'home.html')

polls/views.py
from .models import Question
from django.shortcuts import render, get_object_or_404


def question_list(request):
   questions = Question.objects.all()
   return render(request, 'polls/question_list.html', {'questions': questions})

def question_detail(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/question_detail.html', {'question': question})

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Strona główna</title>
</head>
<body>
<h1>Strona główna</h1>
{% if user.is_authenticated %}
<p>Cześć {{ user }}</p>
{% else %}
<p>Nie jesteś zalogowany</p>
{% endif %}


<a href="{% url 'polls:question_list' %}"><button>Polls</button></a>
</body>
</html>

templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<h1>{{ question.pub_date }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} ({{ choice.votes }})</li>
{% endfor %}
</ul>

templates/polls/question_list.html
<!DOCTYPE html>
<html>

<body>
<div>
   {% for question in questions %}
       <li><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_text }}</a></li>

   {% endfor %}
</div>
</body>
</html>